#!/usr/bin/env node

/**
 * CHANGELOG.mdを自動生成するスクリプト
 *
 * 使用方法:
 * tsx scripts/generate-changelog.ts
 *
 * 初回実装: changelog-data.json から生成
 * 将来的には: Gitのコミット履歴から自動生成に対応
 *
 * 出力先: public/CHANGELOG.md
 */

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const CHANGELOG_DATA_PATH = path.join(__dirname, "../changelog-data.json");
const OUTPUT_DIR = path.join(__dirname, "../public");

/**
 * チェンジログエントリの型定義
 */
interface ChangelogEntry {
  version: string;
  date: string;
  added?: string[] | { ja: string[]; en: string[] };
  changed?: string[] | { ja: string[]; en: string[] };
  fixed?: string[] | { ja: string[]; en: string[] };
}

/**
 * JSONファイルからチェンジログデータを読み込む
 */
function loadChangelogData(): ChangelogEntry[] {
  try {
    if (!fs.existsSync(CHANGELOG_DATA_PATH)) {
      console.warn(
        `⚠️  ${CHANGELOG_DATA_PATH} が見つかりません。デフォルトのチェンジログを生成します。`
      );
      return [];
    }

    const content = fs.readFileSync(CHANGELOG_DATA_PATH, "utf8");
    const data = JSON.parse(content);

    if (!Array.isArray(data)) {
      throw new Error("changelog-data.json must contain an array of entries");
    }

    return data;
  } catch (error) {
    console.error(`❌ エラー: ${error instanceof Error ? error.message : String(error)}`);
    return [];
  }
}

/**
 * 日時をJST形式でフォーマット
 */
function formatJSTDateTime(date: Date): string {
  // JST (UTC+9) に変換
  const jstDate = new Date(date.getTime() + 9 * 60 * 60 * 1000);
  const year = jstDate.getUTCFullYear();
  const month = jstDate.getUTCMonth() + 1;
  const day = jstDate.getUTCDate();
  const hour = jstDate.getUTCHours();
  const minute = jstDate.getUTCMinutes();

  return `${year}年${month}月${day}日 ${String(hour).padStart(2, "0")}:${String(minute).padStart(2, "0")}`;
}

/**
 * チェンジログエントリの型定義
 */
interface ChangelogEntry {
  version: string;
  date: string;
  added?: string[] | { ja: string[]; en: string[] };
  changed?: string[] | { ja: string[]; en: string[] };
  fixed?: string[] | { ja: string[]; en: string[] };
}

/**
 * チェンジログエントリをMarkdown形式に変換
 */
function formatChangelogEntry(entry: ChangelogEntry, locale: "ja" | "en"): string {
  const { version, date } = entry;

  // 多言語対応のデータ構造を判定
  const isMultilingual = (arr: unknown): arr is { ja: string[]; en: string[] } => {
    return typeof arr === "object" && arr !== null && "ja" in arr && "en" in arr;
  };

  const getItems = (items: string[] | { ja: string[]; en: string[] } | undefined): string[] => {
    if (!items) return [];
    if (Array.isArray(items)) return items; // 旧形式の互換性
    return isMultilingual(items) ? items[locale] : [];
  };

  const added = getItems(entry.added);
  const changed = getItems(entry.changed);
  const fixed = getItems(entry.fixed);

  // 言語ごとの見出し
  const headings = {
    ja: {
      title: "チェンジログ",
      description:
        "このファイルは自動生成されています。\n`scripts/generate-changelog.ts` を実行して更新してください。",
      empty: "更新履歴は準備中です。",
      added: "追加",
      changed: "変更",
      fixed: "修正",
      generatedAt: "生成日時",
    },
    en: {
      title: "Changelog",
      description:
        "This file is automatically generated.\nRun `scripts/generate-changelog.ts` to update.",
      empty: "Update history is being prepared.",
      added: "Added",
      changed: "Changed",
      fixed: "Fixed",
      generatedAt: "Generated at",
    },
  };

  const t = headings[locale];

  let markdown = `## [${version}] - ${date}\n\n`;

  if (added.length > 0) {
    markdown += `### ${t.added}\n`;
    added.forEach(item => {
      markdown += `- ${item}\n`;
    });
    markdown += "\n";
  }

  if (changed.length > 0) {
    markdown += `### ${t.changed}\n`;
    changed.forEach(item => {
      markdown += `- ${item}\n`;
    });
    markdown += "\n";
  }

  if (fixed.length > 0) {
    markdown += `### ${t.fixed}\n`;
    fixed.forEach(item => {
      markdown += `- ${item}\n`;
    });
    markdown += "\n";
  }

  return markdown;
}

/**
 * CHANGELOG.mdを生成
 */
function generateChangelog(locale: "ja" | "en") {
  const entries = loadChangelogData();

  const headings = {
    ja: {
      title: "チェンジログ",
      description:
        "このファイルは自動生成されています。\n`scripts/generate-changelog.ts` を実行して更新してください。",
      empty: "更新履歴は準備中です。",
      added: "追加",
      changed: "変更",
      fixed: "修正",
      generatedAt: "生成日時",
    },
    en: {
      title: "Changelog",
      description:
        "This file is automatically generated.\nRun `scripts/generate-changelog.ts` to update.",
      empty: "Update history is being prepared.",
      added: "Added",
      changed: "Changed",
      fixed: "Fixed",
      generatedAt: "Generated at",
    },
  };

  const t = headings[locale];

  let markdown = `# ${t.title}\n\n${t.description}\n\n`;

  if (entries.length === 0) {
    markdown += `## ${t.empty}\n\n---\n${t.generatedAt}: ${formatJSTDateTime(new Date())}\n`;
  } else {
    entries.forEach(entry => {
      markdown += formatChangelogEntry(entry, locale);
    });

    markdown += `---\n${t.generatedAt}: ${formatJSTDateTime(new Date())}\n`;
  }

  // 出力ディレクトリが存在しない場合は作成
  if (!fs.existsSync(OUTPUT_DIR)) {
    fs.mkdirSync(OUTPUT_DIR, { recursive: true });
  }

  // ファイルに出力
  const outputPath = path.join(OUTPUT_DIR, `CHANGELOG_${locale}.md`);
  fs.writeFileSync(outputPath, markdown, "utf8");
  console.log(`✅ CHANGELOG_${locale}.mdを ${outputPath} に出力しました`);
}

/**
 * メイン処理
 */
function main() {
  try {
    console.log("チェンジログ生成を開始...");
    generateChangelog("ja");
    generateChangelog("en");
  } catch (error) {
    console.error(
      "❌ エラーが発生しました:",
      error instanceof Error ? error.message : String(error)
    );
    process.exit(1);
  }
}

// スクリプトが直接実行された場合のみメイン処理を実行
main();

export { formatChangelogEntry, generateChangelog, loadChangelogData };
