name: Code Quality

on:
  pull_request:
    branches:
      - develop
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  # コードサイズ分析
  bundle-size:
    name: Bundle Size Analysis
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Analyze bundle size
        run: |
          echo "📦 Bundle Size Analysis"
          du -sh dist/
          echo ""
          echo "📄 Individual file sizes:"
          find dist -type f -name "*.js" -o -name "*.css" | while read file; do
            size=$(du -h "$file" | cut -f1)
            echo "$size - $file"
          done

      - name: Comment PR with bundle size
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const { execSync } = require('child_process');
            
            const distSize = execSync('du -sh dist/').toString().trim();
            
            const comment = `## 📦 Bundle Size Report
            
            **Total size:** ${distSize.split('\t')[0]}
            
            Built successfully! ✅`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });

  # 重複コード検出
  code-duplication:
    name: Code Duplication Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install jscpd
        run: npm install -g jscpd

      - name: Run duplication detection
        run: |
          jscpd src/ --min-lines 10 --min-tokens 50 --format "typescript,tsx" --ignore "**/__tests__/**,**/*.test.ts,**/*.test.tsx" || true
        continue-on-error: true
